### ISSUE TITLE
Syntax error and buzzwordCRM tests fail

### ISSUE THREAD

**Issue by oalbacha** [calendly/buzzwordcrm#27]
Hey team,
I'm trying to test the API but the app seems to be broken:
![image](https://user-images.githubusercontent.com/17005317/167115282-1b4fd41e-6222-4ea4-8ef6-7e1e6874ea9c.png)
Could you please take a look? Thanks!

**Comment by tristanoneil** [comment]
Hi @oalbacha!

Sorry about that, the README needs to be updated. In order to generate bundle.js ESBuild needs to be run. The easiest way to do that is:

```
npm run esbuild -- --watch
```
