### ISSUE TITLE
Redirection not handled while signing up via Oauth

### ISSUE THREAD

**Issue by aditya314** [calendly/buzzwordcrm#3]
Steps to recreate:
1. Run the project locally.
2. Sign up to Calendly via any new email, it redirects to calendly site and never redirects to the log in page/ dashboard.

This works perfectly well when I log in.

Can anyone help on how to solve this issue, where redirection is taken care of?

**Comment by tcampb** [comment]
Hi @aditya314,

We have a separate authorization route that is currently in beta that will redirect the user to the authorization screen after they create their account and complete the initial onboarding flow.

You can change the authorization url [here](https://github.com/calendly/buzzwordcrm/blob/main/calendlyOauth2Strategy/index.js#L13) to `/partner/oauth/authorize` to use the route described above.

**Comment by ramene** [comment]
Running into similar issues as @aditya314.  Upon making the suggested change to `/partner/oauth/authorize` I am seeing the following error:

`{"message":"no Route matched with those values"}`

Neither path ever redirects to dashboard.
