### ISSUE TITLE
After cloning and updatin the clinetid not able to run npm start giving this error 

### ISSUE THREAD

**Issue by moulikamsali** [calendly/buzzwordcrm#9]
> buzzwordcrm@0.0.0 start C:\Personal\hn\buzzwordcrm
> node app.js

C:\Personal\hn\buzzwordcrm\node_modules\passport-oauth2\lib\strategy.js:86
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at new OAuth2Strategy (C:\Personal\hn\buzzwordcrm\node_modules\passport-oauth2\lib\strategy.js:86:34)
    at Object.<anonymous> (C:\Personal\hn\buzzwordcrm\calendlyOauth2Strategy\index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Personal\hn\buzzwordcrm\app.js:38:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! buzzwordcrm@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buzzwordcrm@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ChandramouliKamsali(\AppData\Roaming\npm-cache\_logs\2021-04-30T07_44_09_940Z-debug.log
![Capture](https://user-images.githubusercontent.com/71902304/116666345-78c22c80-a9b8-11eb-86dd-61394b38e1e7.PNG)

**Comment by tcampb** [comment]
Hi @moulikamsali,

Based on the error above it sounds like the `CLIENT_ID` environment variable is `undefined` when the application starts.

BuzzwordCRM uses the `dotenv` npm package to load environment variables, including `CLIENT_ID`. By default, this package looks for a file called `.env` which does not exist when you initially clone this repository.

Can you confirm that your `CLIENT_ID` was copied into a new file called `.env`? If it was copied into `.env.example` then you can run the command below to copy these values to the `.env` file.

```shell
cp .env.example .env
```

**Comment by moulikamsali** [comment]
Thanks you @tcampb  for quick answer, Some how not able to debug or customize the code. And not even hitting the break points. Does it require any more config changes.

**Comment by tcampb** [comment]
@moulikamsali - the [`npm start`](https://github.com/calendly/buzzwordcrm/blob/main/package.json#L6) command does not currently enable the [`--inspect`](https://nodejs.org/en/docs/guides/debugging-getting-started/) option which allows you to attach a debugging client to the Node.js process.

You can run the command below to enable this setting:

```bash
node --inspect app.js
```
If you are using Chrome you can visit `chrome://inspect` once the application is running to debug the code.

Additional inspector clients can be found here:
https://nodejs.org/en/docs/guides/debugging-getting-started/#inspector-clients

**Comment by ramyakadari18** [comment]
unable access code from get authorization code.
https://calendly.com/oauth/authorize?response_type=code&redirect_uri=http://localhost:3000/&client_id=adlt8mLF9Ey0fuvTdkUNAFXJDfgeViI6ClA_2o0yBJ0
returning code in querystring.
In order to generate Access token we need code .
"grant_type": "authorization_code",
    "client_id": "adlt8mLF9Ey0fuvTdkUNAFXJDfgeViI6ClA_2o0yBJ0",
    "client_secret": "aOBUd5cOqam00tLPIRK0T2mdjopUX1lRRff_-ta3ciE",
    "code": " ",
    "redirect_uri": "https://localhost:3000/"

Please let us know where we have code generation related code in the application

**Comment by ramyakadari18** [comment]
Want to access these API's from React and .netcore application.
Can we use all the api's from trail version

**Comment by tcampb** [comment]
Hi @ramyakadari18 -

> Want to access these API's from React and .netcore application.
Can we use all the api's from trail version

Yes, Calendly's v1 and v2 api endpoints are available on the trial version.

> Please let us know where we have code generation related code in the application

The BuzzwordCRM code assumes that the oauth application's redirect uri is `http://localhost:3000/oauth/callback`. If you are using a different redirect uri you can move the passport authentication code to your `redirect_uri` router to generate the oauth code:

```javascript
router.get('/', passport.authenticate('oauth2')).get(
    '/callback',
    passport.authenticate('oauth2', {
        successRedirect: '/dashboard',
        failureRedirect: '/'
    })
);
```
https://github.com/calendly/buzzwordcrm/blob/abb6c04d5719e91a4b8d19f5c41bc97088be7cac/routes/oauth.js#L6

**Comment by ramyakadari18** [comment]
Hi @tcampb ,
will be able to access calendly api's from postman??
https://api.calendly.com/scheduled_events?user=https://api.calendly.com/users/AAHAWXMXR6MD7AFB&organization=https://api.calendly.com/organizations/CHDCVWIQ5C4YSUHN&count=20
along with access token

its returning {
    "title": "Unauthenticated",
    "message": "The access token is invalid"
}
Any suggestions!!!

**Comment by tcampb** [comment]
Hi @ramyakadari18,

Yes, Calendly's api can be accessed from Postman. To authorize the request we use the `Bearer Token` Authorization header type. Can you confirm that your Postman request is using this authorization type (see attached screenshot)?
<br>

<img width="1545" alt="Postman" src="https://user-images.githubusercontent.com/33756113/117478388-1378b900-af2d-11eb-9aa7-6e35b9b0b85c.png">

**Comment by tcampb** [comment]
Hi @ramyakadari18,

When a user visits the url above (`/oauth/authorize?client_id=....`) from their browser they will automatically be redirected to your oauth application's `redirect_uri`. 

If your `redirect_uri` is hosting your React application then you can extract the `code` query parameter from the url location when the user is redirected. You can then send a request to your .NET core application that includes the authorization code which can be used to retrieve the user's access_token and refresh_token.


Example:

```
import React from 'react';
import { withRouter } from 'react-router';

const parseAuthorizationCode = (location) => {
    const queryString = (location && location.search) || '';

    return queryString.slice(queryString.indexOf('code=') + 5);
};

class Callback extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            code: parseAuthorizationCode(props.location)
        };
    }

    async componentDidMount() {
       // replace accessTokenRequest with api call to your .NET application
       const { data } = await accessTokenRequest(this.state.code);
    }

    render() {
        return <></>;
    }
}

export default withRouter(Callback);
```
